
[[Instances]]
  Host = "http://tasks.trivago.com"
  Location = "/Users/kbenevento/go/src/github.com/benesgarage/jib"
  MainBranch = "master"
  Port = 80
  Username = "kbenevento"

[[Instances]]
  Host = "http://tasks.trivago.com"
  Location = "/Users/kbenevento/Projects/invoicing-V2"
  MainBranch = "release"
  Port = 80
  Username = "kbenevento"
